#!/bin/bash

#exit on first error
set -e
#need a reference to the path where the script is located, since conf and data resources are relative to this
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#basic machine setup
apt-get update
#make sure to update openssl to mitigate heartbeat vulnerability
apt-get -y upgrade openssl
apt-get -y install gcc python-dev python-pip python-virtualenv python-software-properties software-properties-common nginx uwsgi curl nodejs npm supervisor

#make sure nginx starts on boot
update-rc.d nginx defaults

#setup a virtualenv, activate it, and install all the pip plugins we'll need
virtualenv $DIR/../app/retailmenot/ENV
source $DIR/../app/retailmenot/ENV/bin/activate
pip install -r $DIR/../app/retailmenot/requirements.txt

#elasticsearch recommends Oracle JDK, which requires their proprietary repo
add-apt-repository ppa:webupd8team/java
apt-get -y update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
apt-get -y install oracle-java7-installer

#elasticsearch setup
cd /tmp
#hate to do it, but Docker seems to have issues with cert validation.  Would mitigate by checking in binary if necessary for a prod deploy
wget --no-check-certificate https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.0.deb
sudo dpkg -i elasticsearch-1.1.0.deb
rm elasticsearch-1.1.0.deb
ls /etc/elasticsearch/conf/elasticsearch.yml && rm /etc/elasticsearch/conf/elasticsearch.yml
mkdir -p /etc/elasticsearch/conf
ln -s $DIR/../conf/elasticsearch.yml /etc/elasticsearch/conf/elasticsearch.yml

sudo update-rc.d elasticsearch defaults 95 10
sudo /etc/init.d/elasticsearch start

#update node.js to latest stable
npm cache clean -f
npm install -g n
n stable

$DIR/install_statsd

mkdir -p /web/www
mkdir /web/logs
mkdir -p /web/conf/retailmenot

#create symlinks to all the various config files that need deployed
ln -s $DIR/../app/retailmenot /web/www/retailmenot
ls /etc/nginx/sites-enabled || mkdir -p /etc/nginx/sites-enabled
ln -s $DIR/../conf/nginx/uwsgi_retailmenot /etc/nginx/sites-enabled/uwsgi_retailmenot
ls /etc/supervisor/conf.d || mkdir -p /etc/supervisor/conf.d
ln -s $DIR/../conf/supervisor/uwsgi.conf /etc/supervisor/conf.d/uwsgi.conf
ln -s $DIR/../conf/supervisor/statsd_carbon.conf /etc/supervisor/conf.d/statsd_carbon.conf
ln -s $DIR/../conf/uwsgi/uwsgi.ini /web/conf/retailmenot/uwsgi.ini

#seeding elasticsearch
source $DIR/../app/retailmenot/ENV/bin/activate
python $DIR/../app/retailmenot/retailmenot/manage.py rebuild_index
deactivate

